import React, {useMemo, useState} from 'react'
import {createRoot} from 'react-dom/client'
import {Activity, Bot, Check, ChevronRight, CircleDot, Clock3, Command, Database, GitBranch, Lock, Play, Plus, Search, ShieldCheck, Sparkles, Terminal, Wrench, X} from 'lucide-react'
import './styles.css'

type Agent={name:string;status:'Running'|'Waiting'|'Ready';desc:string;steps:number;cost:string}
const agents:Agent[]=[
 {name:'Research Brief',status:'Running',desc:'Search → rank → synthesize evidence',steps:7,cost:'$0.18'},
 {name:'Release Guard',status:'Waiting',desc:'Inspect diff → policy → approval',steps:5,cost:'$0.07'},
 {name:'Support Triage',status:'Ready',desc:'Classify → enrich → route',steps:6,cost:'$0.11'},
 {name:'Data Steward',status:'Ready',desc:'Validate → redact → publish',steps:8,cost:'$0.22'}
]
const events=[['14:32:08','Tool call approved','web.search','success'],['14:31:54','Policy check passed','secrets.scan','success'],['14:31:41','Model step completed','planner.route','info'],['14:31:17','Human approval requested','release.publish','warn']]
function App(){
 const [active,setActive]=useState('Command center'); const [query,setQuery]=useState(''); const [selected,setSelected]=useState('Research Brief'); const [running,setRunning]=useState(false); const [toast,setToast]=useState('')
 const filtered=useMemo(()=>agents.filter(a=>(a.name+a.desc).toLowerCase().includes(query.toLowerCase())),[query])
 const run=()=>{setRunning(true);setToast('Workflow queued in guarded mode');setTimeout(()=>{setRunning(false);setToast('Run completed — 7 steps evaluated')},1400)}
 return <div className="app">
  <aside className="rail"><div className="mark"><Command size={18}/></div><nav>{[['Command center',Activity],['Agents',Bot],['Workflows',GitBranch],['Tools',Wrench],['Approvals',ShieldCheck],['Context',Database],['Audit log',Terminal]].map(([label,Icon])=><button className={active===label?'nav active':'nav'} onClick={()=>setActive(label as string)} key={label as string}><Icon size={18}/><span>{label as string}</span></button>)}</nav><div className="railFoot"><Lock size={15}/><span>Guarded</span></div></aside>
  <main><header><div><div className="eyebrow"><CircleDot size={10}/> CONTROL PLANE / {active.toUpperCase()}</div><h1>Agent command center</h1><p>Plan, govern, execute, and observe autonomous workflows without losing the human in the loop.</p></div><div className="headerActions"><button className="ghost"><Search size={17}/> Search</button><button className="primary" onClick={run}><Play size={16}/>{running?'Running…':'Run workflow'}</button></div></header>
  {toast&&<div className="toast"><Check size={16}/>{toast}<button onClick={()=>setToast('')}><X size={14}/></button></div>}
  <section className="metrics"><Metric icon={Activity} label="Active runs" value="08" meta="+3 this hour"/><Metric icon={ShieldCheck} label="Policy pass rate" value="99.2%" meta="last 24h"/><Metric icon={Clock3} label="Avg. latency" value="2.8s" meta="−14% vs last week"/><Metric icon={Sparkles} label="Est. spend" value="$4.82" meta="today · 31 runs"/></section>
  <section className="workspace"><div className="panel agents"><div className="panelHead"><div><span className="kicker">ORCHESTRATION</span><h2>Agent fleet</h2></div><button className="iconBtn"><Plus size={17}/></button></div><div className="search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Filter agents…"/></div>{filtered.map(a=><button key={a.name} className={selected===a.name?'agent selected':'agent'} onClick={()=>setSelected(a.name)}><div className="agentTop"><span className={'dot '+a.status.toLowerCase()}></span><strong>{a.name}</strong><span className="status">{a.status}</span></div><p>{a.desc}</p><div className="agentMeta"><span>{a.steps} steps</span><span>{a.cost} est.</span><ChevronRight size={15}/></div></button>)}</div>
  <div className="panel canvas"><div className="panelHead"><div><span className="kicker">WORKFLOW / LIVE</span><h2>{selected}</h2></div><span className="live"><span></span> Guarded execution</span></div><div className="flow"><Node n="01" icon={Sparkles} title="Plan intent" text="Planner decomposes request" done/><div className="line"/><Node n="02" icon={Wrench} title="Select tools" text="Policy-aware capability match" done/><div className="line"/><Node n="03" icon={ShieldCheck} title="Gate action" text="Approval required for publish" active/><div className="line dashed"/><Node n="04" icon={Bot} title="Execute" text="Awaiting approval"/></div><div className="approval"><div><span className="kicker">HUMAN GATE</span><strong>Publish research brief?</strong><p>release.publish wants to write to the connected workspace.</p></div><div><button className="ghost">Deny</button><button className="approve" onClick={run}><Check size={15}/> Approve once</button></div></div></div>
  <div className="panel inspector"><div className="panelHead"><div><span className="kicker">INSPECTOR</span><h2>Run context</h2></div></div><Info label="Run ID" value="run_8F2C91"/><Info label="Model route" value="fast → reasoning"/><Info label="Policy" value="strict / default-deny"/><Info label="Memory" value="session + approved"/><div className="miniGraph"><div className="graphTitle">Token budget <b>62%</b></div><div className="bar"><i/></div><small>6,240 / 10,000 tokens</small></div><button className="outline"><Terminal size={15}/> Open trace</button></div></section>
  <section className="panel audit"><div className="panelHead"><div><span className="kicker">OBSERVABILITY</span><h2>Recent activity</h2></div><button className="outline">View audit log <ChevronRight size={15}/></button></div><div className="events">{events.map(e=><div className="event" key={e[0]}><time>{e[0]}</time><div className={'eventDot '+e[3]}></div><div><strong>{e[1]}</strong><span>{e[2]}</span></div><em>{e[3]==='warn'?'Needs review':e[3]==='success'?'Allowed':'Recorded'}</em></div>)}</div></section>
  <footer>AI Agent Command Center · Local-first demo control plane · No external model API required</footer>
 </main></div>
}
function Metric({icon:Icon,label,value,meta}:{icon:any;label:string;value:string;meta:string}){return <div className="metric"><Icon size={17}/><span>{label}</span><strong>{value}</strong><small>{meta}</small></div>}
function Node({n,icon:Icon,title,text,done,active}:{n:string;icon:any;title:string;text:string;done?:boolean;active?:boolean}){return <div className={'node '+(active?'active':'')}><div className="nodeIcon"><Icon size={17}/></div><div><span>{n}</span><strong>{title}{done&&<Check size={13}/>}</strong><p>{text}</p></div></div>}
function Info({label,value}:{label:string;value:string}){return <div className="info"><span>{label}</span><b>{value}</b></div>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>)
